In [1]:
# -*- coding: utf-8 -*-
"""
Analyse de plusieurs séries temporelles financières
===================================================

Ce script peut être exécuté tel quel (python timeseries_financial_analysis.py)
ou copié par cellules dans un notebook Jupyter.

Hypothèses sur les données :
- Première colonne : dates
- Colonnes suivantes : prix, NAV ou indices (une colonne = une série)

Les statistiques de performance (Sharpe, volatilité, rendement annualisé, etc.)
sont calculées à partir des **rendements journaliers** (voir docstrings).

Auteur : généré pour un usage pédagogique — à adapter librement.
"""

from __future__ import annotations

import pathlib
from typing import Optional, Union

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats as scipy_stats

from pathlib import Path # pour le notebook

# ---------------------------------------------------------------------------
# Paramètres globaux (faciles à modifier)
# ---------------------------------------------------------------------------

# Nombre de jours de bourse par an (marchés US / Europe courants)
TRADING_DAYS_PER_YEAR = 252

# Taux sans risque annualisé (ex. 0.02 = 2 % par an). Utilisé pour le Sharpe.
# Par défaut : 0 (comme demandé).
RISK_FREE_ANNUAL = 0.0

# Chemin du CSV réel (None = on génère des données fictives)
CSV_PATH: Optional[str] = '../data_folder/Bitcoin_history_data.csv'  # ex. : r"C:\chemin\vers\donnees.csv"

# Export des tableaux (None = pas d'export)
EXPORT_DIR: Optional[str] = None  # ex. : r"C:\chemin\vers\exports"

In [2]:
CSV_PATH

df = pd.read_csv(CSV_PATH)
df

,Date,Close,High,Low,Open,Volume
0,2015-01-01,314.248993,320.434998,314.002991,320.434998,8036550
1,2015-01-02,315.032013,315.838989,313.565002,314.079010,7860650
2,2015-01-03,281.082001,315.149994,281.082001,314.846008,33054400
3,2015-01-04,264.195007,287.230011,257.612000,281.145996,55629100
4,2015-01-05,274.473999,278.341003,265.084015,265.084015,43962800
...,...,...,...,...,...,...
4105,2026-03-29,65954.921875,67052.953125,64971.707031,66319.695312,21645889785
4106,2026-03-30,66691.445312,68087.289062,65759.804688,65958.351562,37694994180
4107,2026-03-31,68233.312500,68495.273438,65950.437500,66694.585938,42997691338
4108,2026-04-01,68078.554688,69230.359375,67555.359375,68232.890625,36465393617
4109,2026-04-02,67384.445312,68588.539062,65788.750000,68095.265625,39085457408

In [3]:

# =============================================================================
# 1. PRÉPARATION DES DONNÉES
# =============================================================================


def load_or_build_prices(
    csv_path: Optional[str] = None,
    date_column: str = "date",
) -> pd.DataFrame:
    """
    Charge un CSV ou construit un jeu de données fictif pour tester.

    Retourne un DataFrame avec :
    - un index Datetime trié
    - uniquement des colonnes numériques (les séries)

    La première colonne du fichier est supposée être la date (nom par défaut
    'date' si besoin de renommer — adapter selon votre fichier).
    """
    if csv_path is not None and pathlib.Path(csv_path).is_file():
        df = pd.read_csv(csv_path)
        # Si la première colonne n'a pas de nom "date", on prend la 1ère colonne
        if date_column not in df.columns:
            first = df.columns[0]
            df = df.rename(columns={first: date_column})
        df[date_column] = pd.to_datetime(df[date_column])
        df = df.set_index(date_column).sort_index()
        numeric = df.select_dtypes(include=[np.number])
        return numeric

    # --- Données fictives : 3 séries corrélées sur ~2 ans de jours ouvrés ---
    rng = np.random.default_rng(42)
    dates = pd.bdate_range(start="2022-01-01", periods=520, freq="B")
    n = len(dates)
    # Bruit commun + spécifique pour chaque actif
    common = rng.normal(0.0003, 0.008, size=n)
    rets = np.column_stack(
        [
            common + rng.normal(0.0002, 0.006, size=n),
            common * 0.7 + rng.normal(0.0001, 0.010, size=n),
            rng.normal(0.0004, 0.012, size=n),
        ]
    )
    prices = 100 * np.cumprod(1 + rets, axis=0)
    return pd.DataFrame(
        {"Serie_A": prices[:, 0], "Serie_B": prices[:, 1], "Serie_C": prices[:, 2]},
        index=dates,
    )


def prepare_price_frame(
    df: pd.DataFrame,
    *,
    fill_method: str = "ffill",
    drop_remaining_na: bool = True,
) -> pd.DataFrame:
    """
    Nettoie un DataFrame de prix déjà indexé par datetime.

    - fill_method : 'ffill' (propager la dernière valeur) ou 'bfill' ou None
    - drop_remaining_na : supprime les lignes où il reste des NaN après fill

    Vérifie que les colonnes sont numériques exploitables.
    """
    if not isinstance(df.index, pd.DatetimeIndex):
        raise TypeError("L'index doit être un DatetimeIndex.")

    out = df.sort_index().copy()
    # On ne garde que les colonnes numériques
    out = out.select_dtypes(include=[np.number])
    if out.empty:
        raise ValueError("Aucune colonne numérique trouvée.")

    if fill_method == "ffill":
        out = out.ffill()
    elif fill_method == "bfill":
        out = out.bfill()
    elif fill_method is not None:
        raise ValueError("fill_method doit être 'ffill', 'bfill' ou None.")

    if drop_remaining_na:
        out = out.dropna(how="any")

    if out.empty:
        raise ValueError("Après nettoyage, le DataFrame est vide.")

    return out

In [4]:
# =============================================================================
# 2. GRAPHIQUE EN BASE 100
# =============================================================================


def rebase_to_100(prices: pd.DataFrame) -> pd.DataFrame:
    """
    Rebaser chaque colonne à 100 sur sa **première valeur non-NaN**.

    Formule : 100 * prix_t / prix_premier_observation
    """
    base = prices.apply(lambda s: s.dropna().iloc[0] if s.notna().any() else np.nan)
    return 100.0 * prices.div(base, axis=1)


def plot_base100(
    rebased: pd.DataFrame,
    title: str = "Évolution en base 100",
    save_path: Optional[str] = None,
    show: bool = True,
) -> None:
    """
    Trace toutes les séries rebasées sur un même graphique.

    - save_path : si renseigné, enregistre l'image (pratique en exécution .py sans GUI).
    - show : affiche la fenêtre matplotlib (typique en notebook / IDE interactif).
    """
    fig, ax = plt.subplots(figsize=(11, 6))
    for col in rebased.columns:
        ax.plot(rebased.index, rebased[col], label=col, linewidth=1.5)
    ax.axhline(100, color="gray", linestyle="--", linewidth=0.8, alpha=0.7)
    ax.set_title(title)
    ax.set_xlabel("Date")
    ax.set_ylabel("Indice (base 100 au premier point)")
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"Graphique enregistré : {save_path}")
    if show:
        plt.show()
    else:
        plt.close(fig)


# =============================================================================
# 3. RENDEMENTS MENSUELS (tableau)
# =============================================================================


def monthly_returns_from_prices(prices: pd.DataFrame) -> pd.DataFrame:
    """
    Rendements mensuels simples entre **derniers cours disponibles** de chaque mois.

    - Les mois sont en lignes (index de type fin de mois / Period M)
    - Les séries restent en colonnes

    Méthode : dernier cours du mois (resample 'ME' = month end), puis pct_change.
    """
    month_end = prices.resample("ME").last()
    monthly_rets = month_end.pct_change()
    # Index plus lisible : année-mois
    monthly_rets.index = monthly_rets.index.to_period("M").astype(str)
    return monthly_rets.iloc[1:]  # première ligne NaN (pas de mois précédent)


def format_monthly_returns_for_display(
    monthly_rets: pd.DataFrame,
    pct_decimals: int = 2,
) -> pd.DataFrame:
    """Version affichage : pourcentages arrondis (copie, ne modifie pas les données brutes)."""
    return (monthly_rets * 100).round(pct_decimals)

In [5]:
def monthly_performance_table(
    monthly_rets: pd.DataFrame,
    *,
    series_name: Optional[str] = None,
    pct_decimals: int = 2,
) -> pd.DataFrame:
    """
    Construit un tableau annuel des performances mensuelles :
    - colonnes : Jan, Feb, ..., Dec, Year
    - lignes : annees

    monthly_rets est attendu avec un index mensuel (PeriodIndex "M" ou string "YYYY-MM")
    et une colonne par serie. Le tableau est en pourcentage pour l'affichage.
    """
    if monthly_rets.empty:
        return pd.DataFrame(columns=["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Year"])

    data = monthly_rets.copy()
    if isinstance(data.index, pd.PeriodIndex):
        period_idx = data.index.asfreq("M")
    else:
        period_idx = pd.PeriodIndex(data.index.astype(str), freq="M")

    if series_name is None:
        series_name = str(data.columns[0])
    if series_name not in data.columns:
        raise KeyError(f"Serie introuvable dans monthly_rets : {series_name}")

    s = data[series_name].copy()
    s.index = period_idx
    work = pd.DataFrame(
        {
            "year": s.index.year,
            "month": s.index.month,
            "ret": s.values,
        }
    )

    pivot = work.pivot(index="year", columns="month", values="ret")
    month_order = list(range(1, 13))
    pivot = pivot.reindex(columns=month_order)
    pivot.columns = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

    annual = work.groupby("year")["ret"].apply(lambda x: (1.0 + x).prod() - 1.0)
    table = pivot.join(annual.rename("Year"))

    return (table * 100).round(pct_decimals)

In [6]:

# =============================================================================
# 4. STATISTIQUES DE PERFORMANCE (à partir des rendements **journaliers**)
# =============================================================================


def daily_returns_from_prices(prices: pd.DataFrame) -> pd.DataFrame:
    """
    Rendements journaliers simples : (P_t / P_{t-1}) - 1

    **Important (pédagogique)** : les statistiques annualisées ci-dessous
    (volatilité, Sharpe, rendement annualisé géométrique) utilisent ces
    rendements **journaliers**, puis un facteur sqrt(252) ou 252 selon le cas.
    Le tableau des performances **mensuelles** est séparé (fonction dédiée).
    """
    return prices.pct_change().dropna(how="all")


def annualized_geometric_return(daily: pd.DataFrame, trading_days: int = TRADING_DAYS_PER_YEAR) -> pd.Series:
    """
    Performance annualisée **géométrique** à partir des rendements journaliers :

    ( ∏(1+r_i) )^(252/n) - 1

    où n = nombre d'observations journalières par série.
    """
    n = daily.shape[0]
    if n == 0:
        return pd.Series(dtype=float)
    wealth = (1 + daily).prod(axis=0)
    return wealth ** (trading_days / n) - 1


def annualized_volatility(daily: pd.DataFrame, trading_days: int = TRADING_DAYS_PER_YEAR) -> pd.Series:
    """Volatilité annualisée : écart-type des rendements journaliers * sqrt(252)."""
    return daily.std(axis=0, ddof=1) * np.sqrt(trading_days)


def sharpe_ratio(
    daily: pd.DataFrame,
    risk_free_annual: float = RISK_FREE_ANNUAL,
    trading_days: int = TRADING_DAYS_PER_YEAR,
) -> pd.Series:
    """
    Sharpe annualisé (rendements journaliers, taux sans risque annualisé converti en journalier).

    Sharpe = (E[r_jour] - rf_jour) / σ_jour * sqrt(252)

    avec rf_jour ≈ (1+rf_annual)^(1/252) - 1 (composition), ou approximation rf_annual/252.
    Ici on utilise la **composition** pour rester cohérent avec de petits taux.
    """
    rf_daily = (1.0 + risk_free_annual) ** (1.0 / trading_days) - 1.0
    excess = daily - rf_daily
    mu = excess.mean(axis=0)
    sigma = daily.std(axis=0, ddof=1)
    # Éviter division par zéro
    sharpe = np.where(sigma > 0, mu / sigma * np.sqrt(trading_days), np.nan)
    return pd.Series(sharpe, index=daily.columns)


def max_drawdown_from_prices(prices: pd.DataFrame) -> pd.Series:
    """
    Drawdown maximum sur la courbe de **wealth** normalisée (premier prix = 1).

    DD_t = W_t / max(W_0..W_t) - 1 ; max drawdown = min(DD_t) (valeur négative).
    """
    out = {}
    for col in prices.columns:
        s = prices[col].dropna()
        if s.empty:
            out[col] = np.nan
            continue
        w = s / s.iloc[0]
        running_max = w.cummax()
        dd = w / running_max - 1.0
        out[col] = dd.min()
    return pd.Series(out)


def skewness_kurtosis(daily: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    """Skewness et kurtosis (excess kurtosis = Fisher) par colonne, NaN si série constante."""
    skew = daily.apply(lambda s: scipy_stats.skew(s.dropna(), bias=False))
    kurt = daily.apply(lambda s: scipy_stats.kurtosis(s.dropna(), fisher=True, bias=False))
    return skew, kurt


def performance_stats_table(
    prices: pd.DataFrame,
    daily: pd.DataFrame,
    *,
    risk_free_annual: float = RISK_FREE_ANNUAL,
    trading_days: int = TRADING_DAYS_PER_YEAR,
    round_decimals: int = 4,
) -> pd.DataFrame:
    """
    Tableau unique : une ligne par série, colonnes = métriques demandées.

    Les rendements sous-jacents pour Sharpe / vol / rendement ann. / skew / kurt
    sont les **journaliers**. Le max drawdown est calculé sur les **prix** (NAV).
    """
    ann_ret = annualized_geometric_return(daily, trading_days)
    ann_vol = annualized_volatility(daily, trading_days)
    sharpe = sharpe_ratio(daily, risk_free_annual, trading_days)
    mdd = max_drawdown_from_prices(prices)
    skew, kurt = skewness_kurtosis(daily)

    table = pd.DataFrame(
        {
            "perf_annualisee": ann_ret,
            "volatilite_annualisee": ann_vol,
            "sharpe": sharpe,
            "max_drawdown": mdd,
            "skewness": skew,
            "kurtosis_excess": kurt,
        }
    )
    # Arrondi pour l'affichage (copie)
    return table.round(round_decimals)

In [7]:
# =============================================================================
# 5. EXPORT (CSV / Excel)
# =============================================================================


def export_tables(
    monthly_rets: pd.DataFrame,
    stats: pd.DataFrame,
    directory: Union[str, pathlib.Path],
    prefix: str = "analyse_ts",
) -> None:
    """Exporte les tableaux en CSV ; Excel si openpyxl est disponible."""
    path = pathlib.Path(directory)
    path.mkdir(parents=True, exist_ok=True)

    monthly_path = path / f"{prefix}_rendements_mensuels.csv"
    stats_path = path / f"{prefix}_statistiques.csv"
    monthly_rets.to_csv(monthly_path, encoding="utf-8-sig")
    stats.to_csv(stats_path, encoding="utf-8-sig")
    print(f"CSV écrits : {monthly_path} , {stats_path}")

    try:
        xlsx = path / f"{prefix}_rapport.xlsx"
        with pd.ExcelWriter(xlsx, engine="openpyxl") as writer:
            monthly_rets.to_excel(writer, sheet_name="mensuel")
            stats.to_excel(writer, sheet_name="stats")
        print(f"Excel écrit : {xlsx}")
    except ImportError:
        print("(openpyxl non installé : export Excel ignoré. pip install openpyxl)")

In [8]:
# =============================================================================
# 6. PIPELINE PRINCIPAL
# =============================================================================


def run_full_pipeline(
    prices: pd.DataFrame,
    *,
    risk_free_annual: float = RISK_FREE_ANNUAL,
    export_dir: Optional[str] = EXPORT_DIR,
    figure_save_path: Optional[str] = None,
    show_figure: bool = True,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Enchaîne : base 100, mensuel, stats.

    Retourne (rebased_100, monthly_returns, stats_table).

    figure_save_path : enregistre le graphique (recommandé pour un script .py sans affichage).
    show_figure : True pour plt.show() (notebook / environnement interactif).
    """
    prices_clean = prepare_price_frame(prices)

    # --- Graphique base 100 ---
    rebased = rebase_to_100(prices_clean)
    plot_base100(
        rebased,
        title="Comparaison des séries (base 100)",
        save_path=figure_save_path,
        show=show_figure,
    )

    # --- Mensuel ---
    monthly = monthly_returns_from_prices(prices_clean)
    monthly_display = format_monthly_returns_for_display(monthly)
    print("\n=== Performances mensuelles (en %, arrondi) ===")
    print(monthly_display.to_string())
    print("\n=== Tableau de performance mensuelle (annee x mois) ===")
    for col in monthly.columns:
        monthly_year_table = monthly_performance_table(monthly, series_name=col)
        print(f"\n--- {col} ---")
        print(monthly_year_table.to_string())
    print(
        "\n(NB : valeurs en % pour lecture ; les exports CSV gardent les rendements en decimal.)"
    )

    # --- Stats (journaliers) ---
    daily = daily_returns_from_prices(prices_clean)
    stats = performance_stats_table(
        prices_clean,
        daily,
        risk_free_annual=risk_free_annual,
        round_decimals=4,
    )
    print("\n=== Statistiques de performance ===")
    print(
        "Metriques basees sur les rendements journaliers "
        "(vol annualisee = ecart-type journalier * sqrt(252), etc.). "
        "Max drawdown calcule sur les prix (wealth relatif)."
    )
    print(stats.to_string())

    if export_dir:
        export_tables(monthly, stats, export_dir)

    return rebased, monthly, stats

In [9]:

def main() -> None:
    """Point d'entrée : charge les données, lance l'analyse."""
    prices = load_or_build_prices(csv_path=CSV_PATH)
    # En ligne de commande : on sauvegarde le graphique et on évite plt.show() qui peut bloquer.
    # pour le py !!!!!!!!
    #out_png = pathlib.Path(__file__).with_name("base100_comparaison.png")

    #pour le nb !!!!!!!!!!!!!
    out_png = Path("base100_comparaison.png")

    run_full_pipeline(
        prices,
        risk_free_annual=RISK_FREE_ANNUAL,
        export_dir=EXPORT_DIR,
        figure_save_path=str(out_png),
        show_figure=False,
    )


if __name__ == "__main__":
    main()

Graphique enregistré : base100_comparaison.png

=== Performances mensuelles (en %, arrondi) ===
         Close   High    Low   Open  Volume
date
2015-02  16.92   9.07  15.33  11.96  -40.26
2015-03  -3.95  -2.34  -2.70  -2.39   62.53
2015-04  -3.31  -3.69  -7.31  -8.79   49.16
2015-05  -2.52  -2.63   2.02   3.30  -56.44
2015-06  14.28  14.84  11.50  10.25  202.32
2015-07   8.20   7.87  10.31  11.93  -46.94
2015-08 -19.18 -19.73 -19.99 -20.36  -12.35
2015-09   2.61   2.49   4.30   3.28   -4.67
2015-10  33.09  39.98  31.24  38.82  146.15
2015-11  20.10  14.90  19.77  13.07   47.54
2015-12  14.11  13.22  13.05  14.66  -35.85
2016-01 -14.35 -12.14 -12.16 -11.17  -17.61
2016-02  18.69  16.08  17.36  14.58   60.17
2016-03  -4.79  -5.24  -3.81  -4.19   -0.79
2016-04   7.58   8.90   7.81   9.61   15.12
2016-05  18.53  19.98  16.30  17.36   99.72
2016-06  26.71  23.56  22.27  19.92    0.38
2016-07  -7.23  -2.98  -1.92   2.26  -20.26
2016-08  -7.88 -11.82  -8.12 -11.83  -31.56
2016-09   5.95   5.52   5.32   4.87  -26.00
2016-10  14.96  16.33  14.49  16.00   72.95
2016-11   6.38   5.45   6.45   4.79  -13.39
2016-12  29.24  28.85  28.65  30.47   17.92
2017-01   0.69   0.86  -2.77  -4.13   66.02
2017-02  21.60  22.76  27.24  28.21   12.38
2017-03  -9.17  -9.92 -12.39 -13.05  141.83
2017-04  25.76  25.40  28.08  28.76   -7.64
2017-05  69.63  71.46  63.17  65.46  273.95
2017-06   8.50  10.74  15.51  16.10  -44.31
2017-07  15.90  12.91   9.77   8.82    0.04
2017-08  63.58  63.90  67.22  64.86  126.00
2017-09  -7.75  -7.97  -8.54  -8.55  -37.92
2017-10  49.09  48.46  46.68  47.19   91.43
2017-11  58.21  66.93  50.77  61.56  259.56
2017-12  38.33  33.11  38.62  30.19   46.03
2018-01 -27.80 -27.79 -23.35 -21.63  -33.74
2018-02   1.73   6.82   6.30   5.73  -13.74
2018-03 -32.93 -35.00 -33.96 -35.51  -34.35
2018-04  32.51  31.48  33.56  36.76   90.50
2018-05 -18.90 -19.71 -19.70 -21.43  -40.89
2018-06 -14.55 -15.03 -15.58 -16.09  -11.38
2018-07  21.49  26.54  23.86  31.65   16.37
2018-08  -9.55 -13.74 -10.09 -14.76  -14.98
2018-09  -5.85  -5.86  -5.11  -5.29  -10.97
2018-10  -4.65  -4.43  -3.80  -4.05    4.72
2018-11 -36.41 -31.91 -37.58 -32.32   44.30
2018-12  -6.83 -10.51  -5.50  -9.84  -22.92
2019-01  -7.61  -9.41  -7.46  -9.86   25.08
2019-02  11.48  11.45  11.54  10.41   44.05
2019-03   6.50   5.30   6.46   6.68    7.68
2019-04  30.33  30.40  27.60  27.82   53.44
2019-05  60.25  60.10  56.44  58.55   82.76
2019-06  26.15  41.83  32.14  43.41    7.46
2019-07  -6.76 -17.18 -11.12 -19.51  -38.98
2019-08  -4.51  -4.09  -0.69  -0.07  -31.13
2019-09 -13.88 -14.05 -17.85 -15.56   49.42
2019-10  10.92  12.86  15.30  13.55   55.32
2019-11 -17.72 -16.49 -16.76 -15.63  -35.46
2019-12  -4.97  -6.39  -4.60  -6.05   23.37
2020-01  29.98  29.81  28.75  30.35   39.04
2020-02  -8.03  -7.84  -6.84  -8.80   21.61
2020-03 -25.13 -25.88 -25.88 -25.84   -8.40
2020-04  34.48  45.14  33.87  36.81  104.24
2020-05   9.27   2.75  10.54  10.26  -58.53
2020-06  -3.41  -4.97  -3.68  -5.30  -43.34
2020-07  23.92  23.85  20.94  20.95   47.18
2020-08   3.16   3.09   5.56   5.43   -3.78
2020-09  -7.67  -7.83  -8.01  -7.42   98.20
2020-10  27.79  29.32  26.13  24.92  -31.39
2020-11  42.41  40.78  35.08  34.19   57.49
2020-12  47.77  48.08  55.14  58.66   -2.04
2021-01  14.18  17.25  14.43  18.82   12.83
2021-02  36.31  36.25  34.00  34.79    1.31
2021-03  30.53  28.28  33.50  27.57   22.60
2021-04  -1.98  -3.39  -7.96  -9.10  -20.03
2021-05 -35.35 -35.29 -35.55 -33.43  -25.55
2021-06  -6.14  -3.72  -0.45   0.70  -12.69
2021-07  18.79  17.07  20.61  17.51  -24.24
2021-08  13.31  14.11  13.72  11.44   34.60
2021-09  -7.16  -8.50 -11.35 -11.64  -10.33
2021-10  40.03  41.53  44.95  48.85    3.53
2021-11  -7.03  -5.28  -6.69  -6.50   13.86
2021-12 -18.77 -18.00 -18.26 -18.43    0.72
2022-01 -16.89 -20.27 -19.83 -19.61  -43.92
2022-02  12.24  13.23   2.14  -0.57   72.13
2022-03   5.43   8.57  20.98  24.81   -6.62
2022-04 -17.18 -18.40 -16.95 -17.97  -28.30
2022-05 -15.70 -16.82 -17.01 -17.83   40.35
2022-06 -37.77 -37.55 -40.13 -36.61  -21.68
2022-07  17.95  19.76  24.27  17.62  -10.33
2022-08 -14.09 -15.34 -14.93 -16.29   41.06
2022-09  -3.08  -1.52  -2.70  -1.14   32.35
2022-10   5.48   3.41   5.30   5.42    3.85
2022-11 -16.23 -17.33 -18.94 -20.30  -35.35
2022-12  -3.62  -3.27   0.44   0.96  -61.93
2023-01  39.84  39.67  37.83  37.56  103.20
2023-02   0.03   1.55   1.37   2.98  -10.08
2023-03  23.03  21.43  19.53  19.18   -7.47
2023-04   2.78   4.58   5.55   4.33  -22.89
2023-05  -7.00  -7.08  -7.72  -5.28    6.85
2023-06  11.97  12.31  10.18   9.89   68.54
2023-07  -4.09  -5.65  -1.58  -3.82  -55.82
2023-08 -11.29  -6.90 -11.60  -6.75   73.13
2023-09   4.00  -1.33   4.41  -1.43  -73.58
2023-10  28.55  28.15  26.76  28.20  195.59
2023-11   8.78   9.86  10.12   9.74   14.96
2023-12  12.07  12.37  11.90  11.33   -9.49
2024-01   0.75   2.00   0.72   1.88   50.47
2024-02  43.72  45.45  43.03  45.53  165.45
2024-03  16.56  12.25  15.08  11.44  -69.39
2024-04 -15.00  -9.35 -15.09  -8.34   88.72
2024-05  11.30   6.64  12.71   7.09  -27.63
2024-06  -7.13  -8.85  -9.01 -10.93  -36.71
2024-07   3.10   6.23   6.43   8.73   80.54
2024-08  -8.74 -11.04  -8.93 -10.70  -60.36
2024-09   7.39  10.44   6.98  11.02  199.21
2024-10  10.87  10.71  10.68  10.21    9.47
2024-11  37.36  34.18  38.16  34.75  -22.14
2024-12  -3.13  -1.44  -4.40  -4.95   37.90
2025-01   9.61  10.34  10.48  13.05    4.83
2025-02 -17.61 -19.80 -22.94 -19.13   82.82
2025-03  -2.16  -1.37   3.89  -2.80  -65.31
2025-04  14.12  13.57  14.37  14.51   -2.27
2025-05  11.07  10.16  10.92  10.30   37.58
2025-06   2.39   3.69   3.51   4.22    7.86
2025-07   8.05   9.30   8.19   8.72   64.91
2025-08  -6.50  -7.93  -6.41  -7.65  -30.83
2025-09   5.38   4.88   4.29   5.13   22.92
2025-10  -3.95  -3.31  -3.95  -5.33    1.87
2025-11 -17.49 -17.17 -16.52 -16.13  -35.93
2025-12  -3.19  -3.14  -3.61  -2.65  -12.12
2026-01 -10.16  -5.55 -12.99  -4.87  108.33
2026-02 -14.79 -19.52 -16.82 -21.69  -40.35
2026-03   1.85   1.15   4.58   1.24    2.27
2026-04  -1.24   0.14  -0.25   2.10   -9.10

=== Tableau de performance mensuelle (annee x mois) ===

--- Close ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN  16.92  -3.95  -3.31  -2.52  14.28   8.20 -19.18   2.61  33.09  20.10  14.11    97.99
2016 -14.35  18.69  -4.79   7.58  18.53  26.71  -7.23  -7.88   5.95  14.96   6.38  29.24   123.83
2017   0.69  21.60  -9.17  25.76  69.63   8.50  15.90  63.58  -7.75  49.09  58.21  38.33  1368.90
2018 -27.80   1.73 -32.93  32.51 -18.90 -14.55  21.49  -9.55  -5.85  -4.65 -36.41  -6.83   -73.56
2019  -7.61  11.48   6.50  30.33  60.25  26.15  -6.76  -4.51 -13.88  10.92 -17.72  -4.97    92.20
2020  29.98  -8.03 -25.13  34.48   9.27  -3.41  23.92   3.16  -7.67  27.79  42.41  47.77   303.16
2021  14.18  36.31  30.53  -1.98 -35.35  -6.14  18.79  13.31  -7.16  40.03  -7.03 -18.77    59.67
2022 -16.89  12.24   5.43 -17.18 -15.70 -37.77  17.95 -14.09  -3.08   5.48 -16.23  -3.62   -64.27
2023  39.84   0.03  23.03   2.78  -7.00  11.97  -4.09 -11.29   4.00  28.55   8.78  12.07   155.42
2024   0.75  43.72  16.56 -15.00  11.30  -7.13   3.10  -8.74   7.39  10.87  37.36  -3.13   121.05
2025   9.61 -17.61  -2.16  14.12  11.07   2.39   8.05  -6.50   5.38  -3.95 -17.49  -3.19    -6.34
2026 -10.16 -14.79   1.85  -1.24    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -23.00

--- High ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN   9.07  -2.34  -3.69  -2.63  14.84   7.87 -19.73   2.49  39.98  14.90  13.22    85.40
2016 -12.14  16.08  -5.24   8.90  19.98  23.56  -2.98 -11.82   5.52  16.33   5.45  28.85   122.61
2017   0.86  22.76  -9.92  25.40  71.46  10.74  12.91  63.90  -7.97  48.46  66.93  33.11  1391.83
2018 -27.79   6.82 -35.00  31.48 -19.71 -15.03  26.54 -13.74  -5.86  -4.43 -31.91 -10.51   -73.09
2019  -9.41  11.45   5.30  30.40  60.10  41.83 -17.18  -4.09 -14.05  12.86 -16.49  -6.39    89.60
2020  29.81  -7.84 -25.88  45.14   2.75  -4.97  23.85   3.09  -7.83  29.32  40.78  48.08   298.69
2021  17.25  36.25  28.28  -3.39 -35.29  -3.72  17.07  14.11  -8.50  41.53  -5.28 -18.00    65.75
2022 -20.27  13.23   8.57 -18.40 -16.82 -37.55  19.76 -15.34  -1.52   3.41 -17.33  -3.27   -65.69
2023  39.67   1.55  21.43   4.58  -7.08  12.31  -5.65  -6.90  -1.33  28.15   9.86  12.37   157.75
2024   2.00  45.45  12.25  -9.35   6.64  -8.85   6.23 -11.04  10.44  10.71  34.18  -1.44   124.19
2025  10.34 -19.80  -1.37  13.57  10.16   3.69   9.30  -7.93   4.88  -3.31 -17.17  -3.14    -7.30
2026  -5.55 -19.52   1.15   0.14    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -23.00

--- Low ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN  15.33  -2.70  -7.31   2.02  11.50  10.31 -19.99   4.30  31.24  19.77  13.05    93.58
2016 -12.16  17.36  -3.81   7.81  16.30  22.27  -1.92  -8.12   5.32  14.49   6.45  28.65   126.21
2017  -2.77  27.24 -12.39  28.08  63.17  15.51   9.77  67.22  -8.54  46.68  50.77  38.62  1246.61
2018 -23.35   6.30 -33.96  33.56 -19.70 -15.58  23.86 -10.09  -5.11  -3.80 -37.58  -5.50   -70.79
2019  -7.46  11.54   6.46  27.60  56.44  32.14 -11.12  -0.69 -17.85  15.30 -16.76  -4.60    92.43
2020  28.75  -6.84 -25.88  33.87  10.54  -3.68  20.94   5.56  -8.01  26.13  35.08  55.14   293.35
2021  14.43  34.00  33.50  -7.96 -35.55  -0.45  20.61  13.72 -11.35  44.95  -6.69 -18.26    62.47
2022 -19.83   2.14  20.98 -16.95 -17.01 -40.13  24.27 -14.93  -2.70   5.30 -18.94   0.44   -63.95
2023  37.83   1.37  19.53   5.55  -7.72  10.18  -1.58 -11.60   4.41  26.76  10.12  11.90   154.26
2024   0.72  43.03  15.08 -15.09  12.71  -9.01   6.43  -8.93   6.98  10.68  38.16  -4.40   118.85
2025  10.48 -22.94   3.89  14.37  10.92   3.51   8.19  -6.41   4.29  -3.95 -16.52  -3.61    -5.20
2026 -12.99 -16.82   4.58  -0.25    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -24.49

--- Open ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN  11.96  -2.39  -8.79   3.30  10.25  11.93 -20.36   3.28  38.82  13.07  14.66    88.07
2016 -11.17  14.58  -4.19   9.61  17.36  19.92   2.26 -11.83   4.87  16.00   4.79  30.47   125.57
2017  -4.13  28.21 -13.05  28.76  65.46  16.10   8.82  64.86  -8.55  47.19  61.56  30.19  1242.63
2018 -21.63   5.73 -35.51  36.76 -21.43 -16.09  31.65 -14.76  -5.29  -4.05 -32.32  -9.84   -70.02
2019  -9.86  10.41   6.68  27.82  58.55  43.41 -19.51  -0.07 -15.56  13.55 -15.63  -6.05    88.64
2020  30.35  -8.80 -25.84  36.81  10.26  -5.30  20.95   5.43  -7.42  24.92  34.19  58.66   295.39
2021  18.82  34.79  27.57  -9.10 -33.43   0.70  17.51  11.44 -11.64  48.85  -6.50 -18.43    63.55
2022 -19.61  -0.57  24.81 -17.97 -17.83 -36.61  17.62 -16.29  -1.14   5.42 -20.30   0.96   -64.80
2023  37.56   2.98  19.18   4.33  -5.28   9.89  -3.82  -6.75  -1.43  28.20   9.74  11.33   153.87
2024   1.88  45.53  11.44  -8.34   7.09 -10.93   8.73 -10.70  11.02  10.21  34.75  -4.95   119.78
2025  13.05 -19.13  -2.80  14.51  10.30   4.22   8.72  -7.65   5.13  -5.33 -16.13  -2.65    -4.55
2026  -4.87 -21.69   1.24   2.10    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -22.99

--- Volume ---
         Jan     Feb     Mar     Apr     May     Jun    Jul     Aug     Sep     Oct     Nov    Dec      Year
year
2015     NaN  -40.26   62.53   49.16  -56.44  202.32 -46.94  -12.35   -4.67  146.15   47.54 -35.85     97.00
2016  -17.61   60.17   -0.79   15.12   99.72    0.38 -20.26  -31.56  -26.00   72.95  -13.39  17.92    115.53
2017   66.02   12.38  141.83   -7.64  273.95  -44.31   0.04  126.00  -37.92   91.43  259.56  46.03  12142.18
2018  -33.74  -13.74  -34.35   90.50  -40.89  -11.38  16.37  -14.98  -10.97    4.72   44.30 -22.92    -61.59
2019   25.08   44.05    7.68   53.44   82.76    7.46 -38.98  -31.13   49.42   55.32  -35.46  23.37    354.07
2020   39.04   21.61   -8.40  104.24  -58.53  -43.34  47.18   -3.78   98.20  -31.39   57.49  -2.04    120.88
2021   12.83    1.31   22.60  -20.03  -25.55  -12.69 -24.24   34.60  -10.33    3.53   13.86   0.72    -20.92
2022  -43.92   72.13   -6.62  -28.30   40.35  -21.68 -10.33   41.06   32.35    3.85  -35.35 -61.93    -69.60
2023  103.20  -10.08   -7.47  -22.89    6.85   68.54 -55.82   73.13  -73.58  195.59   14.96  -9.49     45.90
2024   50.47  165.45  -69.39   88.72  -27.63  -36.71  80.54  -60.36  199.21    9.47  -22.14  37.90    166.05
2025    4.83   82.82  -65.31   -2.27   37.58    7.86  64.91  -30.83   22.92    1.87  -35.93 -12.12    -22.45
2026  108.33  -40.35    2.27   -9.10     NaN     NaN    NaN     NaN     NaN     NaN     NaN    NaN     15.53

(NB : valeurs en % pour lecture ; les exports CSV gardent les rendements en decimal.)

=== Statistiques de performance ===
Metriques basees sur les rendements journaliers (vol annualisee = ecart-type journalier * sqrt(252), etc.). Max drawdown calcule sur les prix (wealth relatif).
        perf_annualisee  volatilite_annualisee  sharpe  max_drawdown  skewness  kurtosis_excess
Close            0.3899                 0.5576  0.8717       -0.8340   -0.1181           7.9647
High             0.3897                 0.4937  0.9112       -0.8370    0.6728           7.8201
Low              0.3879                 0.5502  0.8777       -0.8318   -0.7238          10.3113
Open             0.3891                 0.5559  0.8714       -0.8338   -0.0740           7.8167
Volume           0.6831                 6.2989  2.4192       -0.9848    2.6997          16.8962

In [10]:
prices = load_or_build_prices(csv_path=CSV_PATH)
prices

,Close,High,Low,Open,Volume
date,,,,,
2015-01-01,314.248993,320.434998,314.002991,320.434998,8036550
2015-01-02,315.032013,315.838989,313.565002,314.079010,7860650
2015-01-03,281.082001,315.149994,281.082001,314.846008,33054400
2015-01-04,264.195007,287.230011,257.612000,281.145996,55629100
2015-01-05,274.473999,278.341003,265.084015,265.084015,43962800
...,...,...,...,...,...
2026-03-29,65954.921875,67052.953125,64971.707031,66319.695312,21645889785
2026-03-30,66691.445312,68087.289062,65759.804688,65958.351562,37694994180
2026-03-31,68233.312500,68495.273438,65950.437500,66694.585938,42997691338
2026-04-01,68078.554688,69230.359375,67555.359375,68232.890625,36465393617
2026-04-02,67384.445312,68588.539062,65788.750000,68095.265625,39085457408

In [11]:
import app.ml_logic.financial_stats as fs

In [12]:

def main2() -> None:
    """Point d'entrée : charge les données, lance l'analyse."""
    prices = load_or_build_prices(csv_path=CSV_PATH)
    # En ligne de commande : on sauvegarde le graphique et on évite plt.show() qui peut bloquer.
    # pour le py !!!!!!!!
    #out_png = pathlib.Path(__file__).with_name("base100_comparaison.png")

    #pour le nb !!!!!!!!!!!!!
    out_png = Path("base100_comparaison.png")

    fs.run_full_financial_pipeline(
        prices,
        risk_free_annual=RISK_FREE_ANNUAL,
        export_dir=EXPORT_DIR,
        figure_save_path=str(out_png),
        show_figure=False,
    )

main2()

Graphique enregistré : base100_comparaison.png

=== Performances mensuelles (en %, arrondi) ===
         Close   High    Low   Open  Volume
date
2015-02  16.92   9.07  15.33  11.96  -40.26
2015-03  -3.95  -2.34  -2.70  -2.39   62.53
2015-04  -3.31  -3.69  -7.31  -8.79   49.16
2015-05  -2.52  -2.63   2.02   3.30  -56.44
2015-06  14.28  14.84  11.50  10.25  202.32
2015-07   8.20   7.87  10.31  11.93  -46.94
2015-08 -19.18 -19.73 -19.99 -20.36  -12.35
2015-09   2.61   2.49   4.30   3.28   -4.67
2015-10  33.09  39.98  31.24  38.82  146.15
2015-11  20.10  14.90  19.77  13.07   47.54
2015-12  14.11  13.22  13.05  14.66  -35.85
2016-01 -14.35 -12.14 -12.16 -11.17  -17.61
2016-02  18.69  16.08  17.36  14.58   60.17
2016-03  -4.79  -5.24  -3.81  -4.19   -0.79
2016-04   7.58   8.90   7.81   9.61   15.12
2016-05  18.53  19.98  16.30  17.36   99.72
2016-06  26.71  23.56  22.27  19.92    0.38
2016-07  -7.23  -2.98  -1.92   2.26  -20.26
2016-08  -7.88 -11.82  -8.12 -11.83  -31.56
2016-09   5.95   5.52   5.32   4.87  -26.00
2016-10  14.96  16.33  14.49  16.00   72.95
2016-11   6.38   5.45   6.45   4.79  -13.39
2016-12  29.24  28.85  28.65  30.47   17.92
2017-01   0.69   0.86  -2.77  -4.13   66.02
2017-02  21.60  22.76  27.24  28.21   12.38
2017-03  -9.17  -9.92 -12.39 -13.05  141.83
2017-04  25.76  25.40  28.08  28.76   -7.64
2017-05  69.63  71.46  63.17  65.46  273.95
2017-06   8.50  10.74  15.51  16.10  -44.31
2017-07  15.90  12.91   9.77   8.82    0.04
2017-08  63.58  63.90  67.22  64.86  126.00
2017-09  -7.75  -7.97  -8.54  -8.55  -37.92
2017-10  49.09  48.46  46.68  47.19   91.43
2017-11  58.21  66.93  50.77  61.56  259.56
2017-12  38.33  33.11  38.62  30.19   46.03
2018-01 -27.80 -27.79 -23.35 -21.63  -33.74
2018-02   1.73   6.82   6.30   5.73  -13.74
2018-03 -32.93 -35.00 -33.96 -35.51  -34.35
2018-04  32.51  31.48  33.56  36.76   90.50
2018-05 -18.90 -19.71 -19.70 -21.43  -40.89
2018-06 -14.55 -15.03 -15.58 -16.09  -11.38
2018-07  21.49  26.54  23.86  31.65   16.37
2018-08  -9.55 -13.74 -10.09 -14.76  -14.98
2018-09  -5.85  -5.86  -5.11  -5.29  -10.97
2018-10  -4.65  -4.43  -3.80  -4.05    4.72
2018-11 -36.41 -31.91 -37.58 -32.32   44.30
2018-12  -6.83 -10.51  -5.50  -9.84  -22.92
2019-01  -7.61  -9.41  -7.46  -9.86   25.08
2019-02  11.48  11.45  11.54  10.41   44.05
2019-03   6.50   5.30   6.46   6.68    7.68
2019-04  30.33  30.40  27.60  27.82   53.44
2019-05  60.25  60.10  56.44  58.55   82.76
2019-06  26.15  41.83  32.14  43.41    7.46
2019-07  -6.76 -17.18 -11.12 -19.51  -38.98
2019-08  -4.51  -4.09  -0.69  -0.07  -31.13
2019-09 -13.88 -14.05 -17.85 -15.56   49.42
2019-10  10.92  12.86  15.30  13.55   55.32
2019-11 -17.72 -16.49 -16.76 -15.63  -35.46
2019-12  -4.97  -6.39  -4.60  -6.05   23.37
2020-01  29.98  29.81  28.75  30.35   39.04
2020-02  -8.03  -7.84  -6.84  -8.80   21.61
2020-03 -25.13 -25.88 -25.88 -25.84   -8.40
2020-04  34.48  45.14  33.87  36.81  104.24
2020-05   9.27   2.75  10.54  10.26  -58.53
2020-06  -3.41  -4.97  -3.68  -5.30  -43.34
2020-07  23.92  23.85  20.94  20.95   47.18
2020-08   3.16   3.09   5.56   5.43   -3.78
2020-09  -7.67  -7.83  -8.01  -7.42   98.20
2020-10  27.79  29.32  26.13  24.92  -31.39
2020-11  42.41  40.78  35.08  34.19   57.49
2020-12  47.77  48.08  55.14  58.66   -2.04
2021-01  14.18  17.25  14.43  18.82   12.83
2021-02  36.31  36.25  34.00  34.79    1.31
2021-03  30.53  28.28  33.50  27.57   22.60
2021-04  -1.98  -3.39  -7.96  -9.10  -20.03
2021-05 -35.35 -35.29 -35.55 -33.43  -25.55
2021-06  -6.14  -3.72  -0.45   0.70  -12.69
2021-07  18.79  17.07  20.61  17.51  -24.24
2021-08  13.31  14.11  13.72  11.44   34.60
2021-09  -7.16  -8.50 -11.35 -11.64  -10.33
2021-10  40.03  41.53  44.95  48.85    3.53
2021-11  -7.03  -5.28  -6.69  -6.50   13.86
2021-12 -18.77 -18.00 -18.26 -18.43    0.72
2022-01 -16.89 -20.27 -19.83 -19.61  -43.92
2022-02  12.24  13.23   2.14  -0.57   72.13
2022-03   5.43   8.57  20.98  24.81   -6.62
2022-04 -17.18 -18.40 -16.95 -17.97  -28.30
2022-05 -15.70 -16.82 -17.01 -17.83   40.35
2022-06 -37.77 -37.55 -40.13 -36.61  -21.68
2022-07  17.95  19.76  24.27  17.62  -10.33
2022-08 -14.09 -15.34 -14.93 -16.29   41.06
2022-09  -3.08  -1.52  -2.70  -1.14   32.35
2022-10   5.48   3.41   5.30   5.42    3.85
2022-11 -16.23 -17.33 -18.94 -20.30  -35.35
2022-12  -3.62  -3.27   0.44   0.96  -61.93
2023-01  39.84  39.67  37.83  37.56  103.20
2023-02   0.03   1.55   1.37   2.98  -10.08
2023-03  23.03  21.43  19.53  19.18   -7.47
2023-04   2.78   4.58   5.55   4.33  -22.89
2023-05  -7.00  -7.08  -7.72  -5.28    6.85
2023-06  11.97  12.31  10.18   9.89   68.54
2023-07  -4.09  -5.65  -1.58  -3.82  -55.82
2023-08 -11.29  -6.90 -11.60  -6.75   73.13
2023-09   4.00  -1.33   4.41  -1.43  -73.58
2023-10  28.55  28.15  26.76  28.20  195.59
2023-11   8.78   9.86  10.12   9.74   14.96
2023-12  12.07  12.37  11.90  11.33   -9.49
2024-01   0.75   2.00   0.72   1.88   50.47
2024-02  43.72  45.45  43.03  45.53  165.45
2024-03  16.56  12.25  15.08  11.44  -69.39
2024-04 -15.00  -9.35 -15.09  -8.34   88.72
2024-05  11.30   6.64  12.71   7.09  -27.63
2024-06  -7.13  -8.85  -9.01 -10.93  -36.71
2024-07   3.10   6.23   6.43   8.73   80.54
2024-08  -8.74 -11.04  -8.93 -10.70  -60.36
2024-09   7.39  10.44   6.98  11.02  199.21
2024-10  10.87  10.71  10.68  10.21    9.47
2024-11  37.36  34.18  38.16  34.75  -22.14
2024-12  -3.13  -1.44  -4.40  -4.95   37.90
2025-01   9.61  10.34  10.48  13.05    4.83
2025-02 -17.61 -19.80 -22.94 -19.13   82.82
2025-03  -2.16  -1.37   3.89  -2.80  -65.31
2025-04  14.12  13.57  14.37  14.51   -2.27
2025-05  11.07  10.16  10.92  10.30   37.58
2025-06   2.39   3.69   3.51   4.22    7.86
2025-07   8.05   9.30   8.19   8.72   64.91
2025-08  -6.50  -7.93  -6.41  -7.65  -30.83
2025-09   5.38   4.88   4.29   5.13   22.92
2025-10  -3.95  -3.31  -3.95  -5.33    1.87
2025-11 -17.49 -17.17 -16.52 -16.13  -35.93
2025-12  -3.19  -3.14  -3.61  -2.65  -12.12
2026-01 -10.16  -5.55 -12.99  -4.87  108.33
2026-02 -14.79 -19.52 -16.82 -21.69  -40.35
2026-03   1.85   1.15   4.58   1.24    2.27
2026-04  -1.24   0.14  -0.25   2.10   -9.10

=== Tableau de performance mensuelle (annee x mois) ===

--- Close ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN  16.92  -3.95  -3.31  -2.52  14.28   8.20 -19.18   2.61  33.09  20.10  14.11    97.99
2016 -14.35  18.69  -4.79   7.58  18.53  26.71  -7.23  -7.88   5.95  14.96   6.38  29.24   123.83
2017   0.69  21.60  -9.17  25.76  69.63   8.50  15.90  63.58  -7.75  49.09  58.21  38.33  1368.90
2018 -27.80   1.73 -32.93  32.51 -18.90 -14.55  21.49  -9.55  -5.85  -4.65 -36.41  -6.83   -73.56
2019  -7.61  11.48   6.50  30.33  60.25  26.15  -6.76  -4.51 -13.88  10.92 -17.72  -4.97    92.20
2020  29.98  -8.03 -25.13  34.48   9.27  -3.41  23.92   3.16  -7.67  27.79  42.41  47.77   303.16
2021  14.18  36.31  30.53  -1.98 -35.35  -6.14  18.79  13.31  -7.16  40.03  -7.03 -18.77    59.67
2022 -16.89  12.24   5.43 -17.18 -15.70 -37.77  17.95 -14.09  -3.08   5.48 -16.23  -3.62   -64.27
2023  39.84   0.03  23.03   2.78  -7.00  11.97  -4.09 -11.29   4.00  28.55   8.78  12.07   155.42
2024   0.75  43.72  16.56 -15.00  11.30  -7.13   3.10  -8.74   7.39  10.87  37.36  -3.13   121.05
2025   9.61 -17.61  -2.16  14.12  11.07   2.39   8.05  -6.50   5.38  -3.95 -17.49  -3.19    -6.34
2026 -10.16 -14.79   1.85  -1.24    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -23.00

--- High ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN   9.07  -2.34  -3.69  -2.63  14.84   7.87 -19.73   2.49  39.98  14.90  13.22    85.40
2016 -12.14  16.08  -5.24   8.90  19.98  23.56  -2.98 -11.82   5.52  16.33   5.45  28.85   122.61
2017   0.86  22.76  -9.92  25.40  71.46  10.74  12.91  63.90  -7.97  48.46  66.93  33.11  1391.83
2018 -27.79   6.82 -35.00  31.48 -19.71 -15.03  26.54 -13.74  -5.86  -4.43 -31.91 -10.51   -73.09
2019  -9.41  11.45   5.30  30.40  60.10  41.83 -17.18  -4.09 -14.05  12.86 -16.49  -6.39    89.60
2020  29.81  -7.84 -25.88  45.14   2.75  -4.97  23.85   3.09  -7.83  29.32  40.78  48.08   298.69
2021  17.25  36.25  28.28  -3.39 -35.29  -3.72  17.07  14.11  -8.50  41.53  -5.28 -18.00    65.75
2022 -20.27  13.23   8.57 -18.40 -16.82 -37.55  19.76 -15.34  -1.52   3.41 -17.33  -3.27   -65.69
2023  39.67   1.55  21.43   4.58  -7.08  12.31  -5.65  -6.90  -1.33  28.15   9.86  12.37   157.75
2024   2.00  45.45  12.25  -9.35   6.64  -8.85   6.23 -11.04  10.44  10.71  34.18  -1.44   124.19
2025  10.34 -19.80  -1.37  13.57  10.16   3.69   9.30  -7.93   4.88  -3.31 -17.17  -3.14    -7.30
2026  -5.55 -19.52   1.15   0.14    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -23.00

--- Low ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN  15.33  -2.70  -7.31   2.02  11.50  10.31 -19.99   4.30  31.24  19.77  13.05    93.58
2016 -12.16  17.36  -3.81   7.81  16.30  22.27  -1.92  -8.12   5.32  14.49   6.45  28.65   126.21
2017  -2.77  27.24 -12.39  28.08  63.17  15.51   9.77  67.22  -8.54  46.68  50.77  38.62  1246.61
2018 -23.35   6.30 -33.96  33.56 -19.70 -15.58  23.86 -10.09  -5.11  -3.80 -37.58  -5.50   -70.79
2019  -7.46  11.54   6.46  27.60  56.44  32.14 -11.12  -0.69 -17.85  15.30 -16.76  -4.60    92.43
2020  28.75  -6.84 -25.88  33.87  10.54  -3.68  20.94   5.56  -8.01  26.13  35.08  55.14   293.35
2021  14.43  34.00  33.50  -7.96 -35.55  -0.45  20.61  13.72 -11.35  44.95  -6.69 -18.26    62.47
2022 -19.83   2.14  20.98 -16.95 -17.01 -40.13  24.27 -14.93  -2.70   5.30 -18.94   0.44   -63.95
2023  37.83   1.37  19.53   5.55  -7.72  10.18  -1.58 -11.60   4.41  26.76  10.12  11.90   154.26
2024   0.72  43.03  15.08 -15.09  12.71  -9.01   6.43  -8.93   6.98  10.68  38.16  -4.40   118.85
2025  10.48 -22.94   3.89  14.37  10.92   3.51   8.19  -6.41   4.29  -3.95 -16.52  -3.61    -5.20
2026 -12.99 -16.82   4.58  -0.25    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -24.49

--- Open ---
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec     Year
year
2015    NaN  11.96  -2.39  -8.79   3.30  10.25  11.93 -20.36   3.28  38.82  13.07  14.66    88.07
2016 -11.17  14.58  -4.19   9.61  17.36  19.92   2.26 -11.83   4.87  16.00   4.79  30.47   125.57
2017  -4.13  28.21 -13.05  28.76  65.46  16.10   8.82  64.86  -8.55  47.19  61.56  30.19  1242.63
2018 -21.63   5.73 -35.51  36.76 -21.43 -16.09  31.65 -14.76  -5.29  -4.05 -32.32  -9.84   -70.02
2019  -9.86  10.41   6.68  27.82  58.55  43.41 -19.51  -0.07 -15.56  13.55 -15.63  -6.05    88.64
2020  30.35  -8.80 -25.84  36.81  10.26  -5.30  20.95   5.43  -7.42  24.92  34.19  58.66   295.39
2021  18.82  34.79  27.57  -9.10 -33.43   0.70  17.51  11.44 -11.64  48.85  -6.50 -18.43    63.55
2022 -19.61  -0.57  24.81 -17.97 -17.83 -36.61  17.62 -16.29  -1.14   5.42 -20.30   0.96   -64.80
2023  37.56   2.98  19.18   4.33  -5.28   9.89  -3.82  -6.75  -1.43  28.20   9.74  11.33   153.87
2024   1.88  45.53  11.44  -8.34   7.09 -10.93   8.73 -10.70  11.02  10.21  34.75  -4.95   119.78
2025  13.05 -19.13  -2.80  14.51  10.30   4.22   8.72  -7.65   5.13  -5.33 -16.13  -2.65    -4.55
2026  -4.87 -21.69   1.24   2.10    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   -22.99

--- Volume ---
         Jan     Feb     Mar     Apr     May     Jun    Jul     Aug     Sep     Oct     Nov    Dec      Year
year
2015     NaN  -40.26   62.53   49.16  -56.44  202.32 -46.94  -12.35   -4.67  146.15   47.54 -35.85     97.00
2016  -17.61   60.17   -0.79   15.12   99.72    0.38 -20.26  -31.56  -26.00   72.95  -13.39  17.92    115.53
2017   66.02   12.38  141.83   -7.64  273.95  -44.31   0.04  126.00  -37.92   91.43  259.56  46.03  12142.18
2018  -33.74  -13.74  -34.35   90.50  -40.89  -11.38  16.37  -14.98  -10.97    4.72   44.30 -22.92    -61.59
2019   25.08   44.05    7.68   53.44   82.76    7.46 -38.98  -31.13   49.42   55.32  -35.46  23.37    354.07
2020   39.04   21.61   -8.40  104.24  -58.53  -43.34  47.18   -3.78   98.20  -31.39   57.49  -2.04    120.88
2021   12.83    1.31   22.60  -20.03  -25.55  -12.69 -24.24   34.60  -10.33    3.53   13.86   0.72    -20.92
2022  -43.92   72.13   -6.62  -28.30   40.35  -21.68 -10.33   41.06   32.35    3.85  -35.35 -61.93    -69.60
2023  103.20  -10.08   -7.47  -22.89    6.85   68.54 -55.82   73.13  -73.58  195.59   14.96  -9.49     45.90
2024   50.47  165.45  -69.39   88.72  -27.63  -36.71  80.54  -60.36  199.21    9.47  -22.14  37.90    166.05
2025    4.83   82.82  -65.31   -2.27   37.58    7.86  64.91  -30.83   22.92    1.87  -35.93 -12.12    -22.45
2026  108.33  -40.35    2.27   -9.10     NaN     NaN    NaN     NaN     NaN     NaN     NaN    NaN     15.53

(NB : valeurs en % pour lecture ; les exports CSV gardent les rendements en decimal.)

=== Statistiques de performance ===
Metriques basees sur les rendements journaliers (vol annualisee = ecart-type journalier * sqrt(252), etc.). Max drawdown calcule sur les prix (wealth relatif).
        perf_annualisee  volatilite_annualisee  sharpe  max_drawdown  skewness  kurtosis_excess
Close            0.3899                 0.5576  0.8717       -0.8340   -0.1181           7.9647
High             0.3897                 0.4937  0.9112       -0.8370    0.6728           7.8201
Low              0.3879                 0.5502  0.8777       -0.8318   -0.7238          10.3113
Open             0.3891                 0.5559  0.8714       -0.8338   -0.0740           7.8167
Volume           0.6831                 6.2989  2.4192       -0.9848    2.6997          16.8962